name: Build-Release
on: 
  push:
    paths-ignore:
      - "README.md"
      - "website/*"
      - ".github/workflows/website.yml"

jobs:
  build-mac:
    name: Build App for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure
        run: |
            mkdir -p build
            cd build
            cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Release ..
      - name: Build 
        run: |
            cd build
            cmake --build . --config Release --target install
      - name: Archive
        run: |
            cd build/release
            zip -r -9 BatchCompress.zip BatchCompress.app/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BatchCompress-macOS
          path: build/release/BatchCompress.zip
                
  build-windows:
    name: Build App for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release .. ;
      - name: Build
        run: |
            cd build
            cmake --build . --config release --target install
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BatchCompress-win64
          path: build\release\BatchCompress.exe

  build-linux:
    name: Build App for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ninja-build build-essential libgtk-3-dev fuse libfuse2
        
      - name: Configure
        run: |
            mkdir build
            cd build
            cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. ;
      - name: Build
        run: |
            cd build
            cmake --build . --config release --target install
      - name: Archive and upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BatchCompress-Linux64
          path: build/Release/BatchCompress.AppImage
